Comment out diff-so-fancy: It's really too fancy

diff --git a/common/.local/bin/diff-highlighter b/common/.local/bin/diff-highlighter
--- a/common/.local/bin/diff-highlighter
+++ b/common/.local/bin/diff-highlighter
@@ -14,9 +14,9 @@ my_name=$(basename "$0")
 # 	exec delta || die "$my_name failed to exec delta"
 # fi
 
-if command -v diff-so-fancy >/dev/null 2>&1; then
-	exec diff-so-fancy || die "$my_name failed to exec diff-so-fancy"
-fi
+# if command -v diff-so-fancy >/dev/null 2>&1; then
+# 	exec diff-so-fancy || die "$my_name failed to exec diff-so-fancy"
+# fi
 
 if command -v diff-highlight >/dev/null 2>&1; then
 	if [[ "$(basename "$0")" = "diff-highlight" ]]; then
